// Line-number index generator — computes exact line ranges for every section (and,
// within `days` sections, every day) in a guide's JSON, so an editor can jump straight
// to `offset:N limit:M` instead of reading or grepping the whole file. Output is a
// sidecar Markdown file (guides/<slug>.index.md) — a `.md` extension deliberately, so
// Astro's glob("**/*.json") loader never picks it up as a guide entry.
//
// The index is GENERATED, not hand-maintained: line numbers drift on every edit, so
// re-run this after any edit that adds/removes lines in a guide. Cheap and safe to run
// anytime; it only reads guide JSON and writes the one sidecar file per guide.
//
// Usage:  node scripts/audit/index-guide.mjs           (all guides)
//         node scripts/audit/index-guide.mjs korea      (one guide)

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { readGuides, GUIDES_DIR, isMain } from "./lib.mjs";

// Turns a char index into a 1-based line number (matches Read-tool line numbering).
function makeLineFinder(text) {
  const starts = [0];
  for (let i = 0; i < text.length; i++) if (text[i] === "\n") starts.push(i + 1);
  return (idx) => {
    let lo = 0, hi = starts.length - 1;
    while (lo < hi) {
      const mid = (lo + hi + 1) >> 1;
      if (starts[mid] <= idx) lo = mid; else hi = mid - 1;
    }
    return lo + 1;
  };
}

// Finds the char index of the `[` that opens `"<key>": [` — the FIRST such match at or
// after fromIdx. Scoping the search window (whole file for "sections", one section's
// slice for "items") keeps this safe even though the same key name can recur elsewhere
// in the file (e.g. every `sights`/`list` section also has an `items` array).
function findArrayStart(text, key, fromIdx = 0) {
  const re = new RegExp(`"${key}"\\s*:\\s*\\[`);
  const m = re.exec(text.slice(fromIdx));
  if (!m) return -1;
  return fromIdx + m.index + m[0].length - 1;
}

// Walks a `[...]` array (text[arrayStartIdx] === '[') and returns the [start, end]
// char-index span (inclusive) of each direct `{...}` child, plus the array's own end
// index. Tracks JSON string state (with backslash-escaping) so braces inside string
// values never get mistaken for structural braces.
function objectChildren(text, arrayStartIdx) {
  let i = arrayStartIdx + 1;
  let depth = 0;
  let inString = false, escape = false;
  let childStart = -1;
  const children = [];
  for (; i < text.length; i++) {
    const c = text[i];
    if (inString) {
      if (escape) escape = false;
      else if (c === "\\") escape = true;
      else if (c === '"') inString = false;
      continue;
    }
    if (c === '"') { inString = true; continue; }
    if (depth === 0) {
      if (c === "{") { childStart = i; depth = 1; }
      else if (c === "]") break;
      continue;
    }
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) { children.push([childStart, i]); childStart = -1; }
    }
  }
  return { children, arrayEnd: i };
}

function buildIndex(raw) {
  const line = makeLineFinder(raw);
  const sectionsArrayStart = findArrayStart(raw, "sections", 0);
  if (sectionsArrayStart === -1) return [];
  const { children } = objectChildren(raw, sectionsArrayStart);

  return children.map(([start, end]) => {
    const slice = raw.slice(start, end + 1);
    let obj;
    try { obj = JSON.parse(slice); } catch { obj = {}; }
    const row = {
      startLine: line(start),
      endLine: line(end),
      group: obj.group || "",
      type: obj.type || "",
      label: obj.title || "",
      days: [],
    };
    if (obj.type === "days") {
      const itemsStart = findArrayStart(raw, "items", start);
      if (itemsStart !== -1 && itemsStart <= end) {
        const { children: dayChildren } = objectChildren(raw, itemsStart);
        row.days = dayChildren.map(([dStart, dEnd]) => {
          const dSlice = raw.slice(dStart, dEnd + 1);
          let d;
          try { d = JSON.parse(dSlice); } catch { d = {}; }
          return {
            startLine: line(dStart),
            endLine: line(dEnd),
            date: d.date || "",
            title: d.title || "",
          };
        });
      }
    }
    return row;
  });
}

function renderMarkdown(slug, totalLines, rows) {
  const lines = [
    `<!-- AUTO-GENERATED by scripts/audit/index-guide.mjs — do not hand-edit.`,
    `     Regenerate after any line-count-changing edit: node scripts/audit/index-guide.mjs ${slug}`,
    `     Line numbers are 1-indexed, matching Read-tool / editor line numbers. -->`,
    ``,
    `# ${slug}.json — line index (${totalLines} lines)`,
    ``,
    `| Lines | Group | Type | Title |`,
    `|---|---|---|---|`,
  ];
  for (const r of rows) {
    lines.push(`| ${r.startLine}–${r.endLine} | ${r.group} | ${r.type} | ${r.label} |`);
    for (const d of r.days) {
      lines.push(`|   ${d.startLine}–${d.endLine} | ↳ ${d.date} | | ${d.title} |`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

export async function indexGuide({ file, slug, raw }) {
  const rows = buildIndex(raw);
  const totalLines = raw.split("\n").length;
  const md = renderMarkdown(slug, totalLines, rows);
  const outPath = path.join(GUIDES_DIR, `${slug}.index.md`);
  await writeFile(outPath, md, "utf8");
  return { slug, outPath, sections: rows.length, days: rows.reduce((n, r) => n + r.days.length, 0) };
}

async function main() {
  const wantSlug = process.argv[2];
  const guides = await readGuides();
  const targets = wantSlug ? guides.filter((g) => g.slug === wantSlug) : guides;
  if (wantSlug && !targets.length) {
    console.error(`[index-guide] no guide matching slug "${wantSlug}"`);
    process.exit(1);
  }
  for (const g of targets) {
    const result = await indexGuide(g);
    console.log(`[index-guide] ${result.slug}: ${result.sections} sections, ${result.days} day-items → ${path.basename(result.outPath)}`);
  }
}

if (isMain(import.meta.url)) main();
