// Tests for scripts/refresh-fx.mjs — the generator that keeps FALLBACK_RATES honest.
// The seed table is not cosmetic: rate.js returns early for any currency missing from it,
// so a currency dropped here silently removes the exchange-rate feature from that guide.
// Zero network — the Frankfurter call is injected.

// @protects-file Exchange rates are refreshed from the published source with the date recorded.

import { describe, it, expect } from "vitest";
import { roundRate, renderBlock, spliceIntoSource, fetchRates, neededCurrencies } from "../refresh-fx.mjs";

describe("roundRate — precision follows magnitude, not currency", () => {
  it("rounds high-magnitude currencies to whole units", () => {
    expect(roundRate(1443.61)).toBe(1444); // KRW
    expect(roundRate(18052.4)).toBe(18052); // IDR
  });
  it("keeps one decimal in the tens", () => {
    expect(roundRate(21.0951)).toBe(21.1); // CZK
  });
  it("keeps three decimals below ten, where EUR/GBP live", () => {
    expect(roundRate(0.8714)).toBe(0.871);
    expect(roundRate(6.5092)).toBe(6.509);
  });
  it("returns null for a non-finite value rather than emitting NaN into source", () => {
    expect(roundRate(undefined)).toBeNull();
    expect(roundRate(NaN)).toBeNull();
  });
});

describe("fetchRates", () => {
  const resp = (rates, date = "2026-07-31") => ({ ok: true, json: async () => ({ rates, date }) });

  it("always includes USD as exactly 1 without asking the API", async () => {
    let askedFor = "";
    const r = await fetchRates(["USD", "JPY"], async (url) => {
      askedFor = url;
      return resp({ JPY: 160.2 });
    });
    expect(r.rates.USD).toBe(1);
    expect(askedFor).not.toMatch(/symbols=.*USD/);
  });

  it("reports currencies the feed does not publish instead of inventing them", async () => {
    const r = await fetchRates(["JPY", "VND", "ARS"], async () => resp({ JPY: 160.2 }));
    expect(r.rates.JPY).toBe(160);
    expect(r.rates).not.toHaveProperty("VND");
    expect(r.rates).not.toHaveProperty("ARS");
    expect(r.missing.sort()).toEqual(["ARS", "VND"]);
  });

  it("throws a named error on a non-ok response rather than writing a broken table", async () => {
    await expect(fetchRates(["JPY"], async () => ({ ok: false, status: 503 }))).rejects.toThrow(/503/);
  });
});

describe("renderBlock / spliceIntoSource", () => {
  it("emits a parseable block carrying the as-of date", () => {
    const block = renderBlock({ USD: 1, JPY: 160 }, "2026-07-31");
    expect(block).toContain('export const FALLBACK_RATES_AS_OF = "2026-07-31";');
    expect(block).toContain("JPY: 160");
    expect(block).toContain("GENERATED by scripts/refresh-fx.mjs");
  });

  it("replaces the existing block in place, leaving surrounding source untouched", () => {
    const src = [
      "const BEFORE = 1;",
      "// Rough fallback FX vs USD (1 USD ≈ N units). APPROX — old text.",
      "export const FALLBACK_RATES = {",
      "  KRW: 1535, DKK: 6.9,",
      "};",
      "const AFTER = 2;",
    ].join("\n");
    const out = spliceIntoSource(src, renderBlock({ USD: 1 }, "2026-07-31"));
    expect(out).toContain("const BEFORE = 1;");
    expect(out).toContain("const AFTER = 2;");
    expect(out).not.toContain("KRW: 1535"); // the stale values are gone
    expect(out).toContain("USD: 1");
  });

  it("throws rather than silently appending when the block can't be found", () => {
    expect(() => spliceIntoSource("const nothing = true;", "x")).toThrow(/not found/);
  });
});

describe("neededCurrencies", () => {
  it("returns a sorted, de-duplicated set of the codes actually in use", () => {
    const codes = neededCurrencies({
      A: { currency: { code: "EUR" } },
      B: { currency: { code: "EUR" } },
      C: { currency: { code: "AUD" } },
      D: {},
    });
    expect(codes).toEqual(["AUD", "EUR"]);
  });
});
