/**
 * Aggregate anonymous usage telemetry into a committed summary the guide-author reads.
 *
 * Reads the RTDB `telemetry` subtree over the REST API — KEYLESS, because that node is
 * `.read: true` (aggregate counts, no PII), so no service account is needed (the reason the
 * whole thing is public-read). Runs the tested `summarize()` and writes:
 *   · docs/telemetry/summary.json — machine-readable, for the guide-author skill
 *   · docs/telemetry/summary.md   — human-readable ranking
 *
 * Invoked weekly by .github/workflows/telemetry-aggregate.yml (which commits any change) and
 * on demand via `npm run aggregate-telemetry`. No-ops cleanly if telemetry is empty or the
 * rules haven't been published yet (a pre-publish read returns 401 → we skip, not fail CI).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { summarize, type GuideSummary } from "../src/features/telemetry/model/telemetry";
import { FIREBASE_CONFIG } from "../src/features/firebase/firebase-config.js";

const url = `${FIREBASE_CONFIG.databaseURL}/telemetry.json`;
const res = await fetch(url);

if (res.status === 401 || res.status === 403) {
  console.log("[telemetry] read denied — publish the hardened rules (telemetry .read: true) first. Skipping, not failing.");
  process.exit(0);
}
if (!res.ok) {
  console.error(`[telemetry] fetch failed: ${res.status} ${res.statusText}`);
  process.exit(1);
}

const raw = await res.json();
const summary = summarize(raw);

mkdirSync("docs/telemetry", { recursive: true });
writeFileSync("docs/telemetry/summary.json", JSON.stringify(summary, null, 2) + "\n");
writeFileSync("docs/telemetry/summary.md", renderMd(summary));
console.log(`[telemetry] summarized ${summary.length} guide(s) → docs/telemetry/`);

function renderMd(guides: GuideSummary[]): string {
  const lines: string[] = [
    "# Telemetry summary — anonymous tab-open counts",
    "",
    "Auto-generated by `scripts/aggregate-telemetry.ts` (weekly). Counts how often each tab is",
    "opened, per guide — no ids, no PII. The `waypoint-guide-author` skill reads this to start the",
    "next guide's tab decisions from evidence instead of doctrine. Do not hand-edit.",
    "",
  ];
  if (!guides.length) {
    lines.push("_No telemetry yet — nothing has been opened, or the rules aren't published._");
    return lines.join("\n") + "\n";
  }
  for (const g of guides) {
    lines.push(`## ${g.guide} — ${g.totalOpens} opens`, "");
    const rank = (label: string, rows: { name: string; count: number }[]) => {
      if (!rows.length) return;
      lines.push(`**${label}**`, "");
      lines.push("| # | name | opens |", "|--:|---|--:|");
      rows.forEach((r, i) => lines.push(`| ${i + 1} | ${r.name} | ${r.count} |`));
      lines.push("");
    };
    rank("Content tabs", g.tabs);
    rank("Tools", g.tools);
  }
  return lines.join("\n") + "\n";
}
