// Regenerates the FALLBACK_RATES table in src/data/countries.mjs from the live ECB feed
// (Frankfurter — the same service the runtime rate pill uses, so the fallback and the live
// value can never come from different worlds).
//
// WHY a fallback table exists at all, given rates are perishable: src/features/live-data/ui/
// rate.js bails out entirely (`if (!curCode || !curFallbackRate) return`) when a guide's
// currency has no fallback — so a MISSING entry doesn't mean "falls back to live", it means
// the guide shows no exchange-rate feature whatsoever. Before this script, 4 of 40 supported
// currencies had an entry and the other 36 silently lost the feature.
//
// These values are seed/offline values, clearly stamped with the date they were fetched. The
// live rate always overrides them at runtime. Re-run whenever they drift enough to mislead:
//   npm run refresh-fx
//
// Honest-blank rule: a currency Frankfurter does not publish is LEFT OUT, never invented or
// interpolated. The script reports exactly which ones, so the gap is visible instead of
// silently filled with a plausible number.

import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import path from "node:path";
import { COUNTRIES } from "../src/data/countries.mjs";

const FRANKFURTER = "https://api.frankfurter.dev/v1/latest";
const TARGET = path.join(process.cwd(), "src", "data", "countries.mjs");

export function neededCurrencies(countries = COUNTRIES) {
  return [...new Set(Object.values(countries).map((c) => c?.currency?.code).filter(Boolean))].sort();
}

// Round to a sensible precision for a seed value: high-magnitude currencies (KRW, VND, IDR)
// don't need decimals; sub-10 rates (EUR, GBP, CHF) need three.
export function roundRate(n) {
  if (!Number.isFinite(n)) return null;
  if (n >= 100) return Math.round(n);
  if (n >= 10) return Math.round(n * 10) / 10;
  return Math.round(n * 1000) / 1000;
}

// Pure: build the replacement source block. Exported so a test can assert its shape without
// touching the network or the real file.
export function renderBlock(rates, asOf) {
  const codes = Object.keys(rates).sort();
  const lines = [];
  for (let i = 0; i < codes.length; i += 6) {
    lines.push("  " + codes.slice(i, i + 6).map((c) => `${c}: ${rates[c]}`).join(", ") + ",");
  }
  return [
    "// Rough fallback FX vs USD (1 USD ≈ N units). APPROX — the live rate overrides these at",
    "// runtime; these exist so a guide still shows SOMETHING offline, and because rate.js",
    "// disables the whole rate feature for a currency with no entry here.",
    "// GENERATED by scripts/refresh-fx.mjs — do not hand-edit; run `npm run refresh-fx`.",
    `export const FALLBACK_RATES_AS_OF = ${JSON.stringify(asOf)};`,
    "export const FALLBACK_RATES = {",
    ...lines,
    "};",
  ].join("\n");
}

export function spliceIntoSource(src, block) {
  // Replace from the first line of the old comment/const through the closing brace.
  const re = /\/\/ Rough fallback FX[\s\S]*?export const FALLBACK_RATES = \{[\s\S]*?\n\};/;
  if (!re.test(src)) throw new Error("FALLBACK_RATES block not found in countries.mjs — has it been renamed?");
  return src.replace(re, block);
}

export async function fetchRates(codes, fetchImpl = fetch) {
  // USD is the base — always 1, never fetched.
  const wanted = codes.filter((c) => c !== "USD");
  const res = await fetchImpl(`${FRANKFURTER}?base=USD&symbols=${wanted.join(",")}`);
  if (!res.ok) throw new Error(`Frankfurter HTTP ${res.status}`);
  const data = await res.json();
  if (!data?.rates) throw new Error("Frankfurter returned no rates object");
  const rates = { USD: 1 };
  const missing = [];
  for (const c of wanted) {
    const v = roundRate(data.rates[c]);
    if (v == null) missing.push(c);
    else rates[c] = v;
  }
  return { rates, missing, date: data.date };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const codes = neededCurrencies();
  console.error(`[fx] ${codes.length} currencies in use; querying Frankfurter…`);
  const { rates, missing, date } = await fetchRates(codes);
  const src = await readFile(TARGET, "utf8");
  await writeFile(TARGET, spliceIntoSource(src, renderBlock(rates, date)));
  console.error(`[fx] wrote ${Object.keys(rates).length} rates, as of ${date}`);
  if (missing.length) {
    // Honest blank, stated out loud — these currencies keep no fallback rather than a guess.
    console.error(`[fx] NOT published by Frankfurter (left out, no rate invented): ${missing.join(", ")}`);
    console.error("[fx] guides in those countries show no offline rate — that is the honest outcome, not a bug to paper over.");
  }
}
